<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>whiteboat_localization</name>
  <version>0.0.0</version>
  <description>Pacote de localização do Whiteboat — fusão GPS + IMU</description>

  <maintainer email="dyfflen@todo.todo">dyfflen</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>geographic_msgs</depend>
  <depend>whiteboat_core</depend>
  <depend>mavros</depend>
  <depend>mavros_msgs</depend>
  <depend>tf2_ros</depend>

  <exec_depend>ros2bag</exec_depend>
  <exec_depend>rosbag2_transport</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
